// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ARSDbContext))]
    [Migration("20260722042202_AddDisplayedNameForRole")]
    partial class AddDisplayedNameForRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AiMatchScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("JobPostingId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("ResumeId");

                    b.ToTable("Application");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiFeedback = "Hồ sơ hoàn hảo. Ứng viên có đầy đủ kỹ năng cứng về C#, EF Core, SQL và Docker trùng khớp hoàn toàn với JD.",
                            AiMatchScore = 95,
                            AppliedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CandidateId = 4,
                            CoverLetter = "Tôi rất mong muốn được làm việc tại FPT.",
                            JobPostingId = 1,
                            ResumeId = 1,
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            AiFeedback = "Ứng viên có kiến thức nền tảng C# nhưng thiếu kinh nghiệm thực tế với SQL và hệ thống lớn theo yêu cầu.",
                            AiMatchScore = 65,
                            AppliedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CandidateId = 5,
                            CoverLetter = "Mong công ty cho cơ hội phỏng vấn.",
                            JobPostingId = 1,
                            ResumeId = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AiFeedback = "Hồ sơ còn khá yếu, chưa đáp ứng được các tiêu chí kỹ thuật tối thiểu của vị trí hiện tại.",
                            AiMatchScore = 40,
                            AppliedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CandidateId = 6,
                            CoverLetter = "Xin thực tập ạ.",
                            JobPostingId = 1,
                            ResumeId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            AiFeedback = "Hồ sơ không phù hợp. Ứng viên làm mảng Marketing, hoàn toàn không có kỹ năng lập trình phần mềm.",
                            AiMatchScore = 10,
                            AppliedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CandidateId = 7,
                            CoverLetter = "Tìm kiếm cơ hội mới.",
                            JobPostingId = 1,
                            ResumeId = 4,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecruiterId")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RecruiterId")
                        .IsUnique();

                    b.HasIndex("TaxCode")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Khu Công nghệ cao Hòa Lạc, Thạch Thất, Hà Nội",
                            CompanyName = "FPT Software",
                            CompanySize = "10000+ nhân viên",
                            LogoPath = "/uploads/logos/fpt-software.png",
                            Overview = "Tập đoàn công nghệ hàng đầu Việt Nam.",
                            RecruiterId = 2,
                            TaxCode = "0101248141",
                            Website = "https://fpt-software.com"
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lập trình viên, Tester, AI Engineer, DevOps...",
                            Name = "Công nghệ thông tin / Phần mềm"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sales Executive, Account Manager, Chăm sóc khách hàng...",
                            Name = "Kinh doanh / Bán hàng"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Digital Marketing, Content Creator, SEO, Event Organizer...",
                            Name = "Marketing / Truyền thông"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kế toán tổng hợp, Kiểm toán viên, Phân tích tài chính...",
                            Name = "Tài chính / Kế toán"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tuyển dụng, C&B, Trợ lý, Quản lý văn phòng...",
                            Name = "Hành chính / Nhân sự"
                        },
                        new
                        {
                            Id = 6,
                            Description = "UI/UX Designer, Graphic Designer, Video Editor...",
                            Name = "Thiết kế / Đồ họa"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Phiên dịch viên Tiếng Anh, Tiếng Trung, Tiếng Nhật...",
                            Name = "Biên phiên dịch / Ngôn ngữ"
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobPosting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxSalary")
                        .HasColumnType("int");

                    b.Property<int?>("MinSalary")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Vacancies")
                        .HasColumnType("int");

                    b.Property<int>("WorkMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("JobPostings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Benefits = "Lương thưởng tháng 13, bảo hiểm FPT Care, làm việc hybrid.",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phát triển các hệ thống Web API quy mô lớn sử dụng .NET 8 và SQL Server.",
                            ExpiredAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobCategoryId = 1,
                            JobType = 1,
                            Location = "Cầu Giấy, Hà Nội",
                            MaxSalary = 25000000,
                            MinSalary = 15000000,
                            Requirements = "Có kinh nghiệm lập trình C#, hiểu biết về Entity Framework Core, SQL Server. Biết Docker là một lợi thế.",
                            Status = 2,
                            Title = "Kỹ Sư Lập Trình Backend .NET",
                            Vacancies = 3,
                            WorkMode = 3
                        },
                        new
                        {
                            Id = 2,
                            Benefits = "Thưởng theo KPIs, môi trường trẻ trung năng động.",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lên kế hoạch và triển khai các chiến dịch quảng cáo trên nền tảng Digital (Facebook, Google).",
                            ExpiredAt = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobCategoryId = 3,
                            JobType = 1,
                            Location = "Thanh Xuân, Hà Nội",
                            MaxSalary = 20000000,
                            MinSalary = 10000000,
                            Requirements = "Tối thiểu 1 năm kinh nghiệm chạy Ads. Có khả năng sáng tạo nội dung.",
                            Status = 2,
                            Title = "Chuyên viên Marketing Digital",
                            Vacancies = 2,
                            WorkMode = 1
                        },
                        new
                        {
                            Id = 3,
                            Benefits = "Hoa hồng cao, phụ cấp ăn trưa và đi lại.",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tư vấn sản phẩm dịch vụ của công ty đến với khách hàng qua điện thoại.",
                            ExpiredAt = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobCategoryId = 2,
                            JobType = 1,
                            Location = "Đống Đa, Hà Nội",
                            MaxSalary = 15000000,
                            MinSalary = 7000000,
                            Requirements = "Giọng nói chuẩn, giao tiếp tốt, không yêu cầu kinh nghiệm (được đào tạo).",
                            Status = 2,
                            Title = "Nhân viên Telesales",
                            Vacancies = 5,
                            WorkMode = 1
                        },
                        new
                        {
                            Id = 4,
                            Benefits = "Hỗ trợ dấu mộc thực tập, trợ cấp 3 triệu/tháng, cơ hội lên nhân viên chính thức.",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tham gia phát triển các tính năng Front-end cho dự án công ty bằng ReactJS.",
                            ExpiredAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobCategoryId = 1,
                            JobType = 3,
                            Location = "Quận 1, TP. HCM",
                            MaxSalary = 5000000,
                            MinSalary = 3000000,
                            Requirements = "Sinh viên năm cuối hoặc mới ra trường, nắm chắc HTML/CSS/JS cơ bản.",
                            Status = 2,
                            Title = "Thực tập sinh ReactJS",
                            Vacancies = 4,
                            WorkMode = 2
                        },
                        new
                        {
                            Id = 5,
                            Benefits = "Chế độ BHYT, BHXH đầy đủ, thưởng lễ tết hấp dẫn.",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chịu trách nhiệm kiểm tra đối chiếu số liệu, lập báo cáo tài chính hàng tháng/quý.",
                            ExpiredAt = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobCategoryId = 4,
                            JobType = 1,
                            Location = "Hải Châu, Đà Nẵng",
                            MaxSalary = 18000000,
                            MinSalary = 12000000,
                            Requirements = "Tốt nghiệp đại học chuyên ngành Kế toán, trên 3 năm kinh nghiệm làm tổng hợp.",
                            Status = 2,
                            Title = "Kế toán tổng hợp",
                            Vacancies = 1,
                            WorkMode = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xem danh sách tin tuyển dụng",
                            Name = "ViewJob"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tạo mới tin tuyển dụng",
                            Name = "CreateJob"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Chỉnh sửa tin tuyển dụng",
                            Name = "EditJob"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xóa tin tuyển dụng",
                            Name = "DeleteJob"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nộp hồ sơ ứng tuyển (CV)",
                            Name = "ApplyJob"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Xem và đánh giá hồ sơ ứng viên",
                            Name = "ReviewCV"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sử dụng trí tuệ nhân tạo (AI) để chấm điểm CV",
                            Name = "EvaluateAI"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Quản lý vai trò và phân quyền hệ thống",
                            Name = "ManageRoles"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Quản lý danh sách người dùng",
                            Name = "ManageUsers"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RecruiterRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RecruiterRequests");
                });

            modelBuilder.Entity("Domain.Entities.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("RawTextContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.ToTable("Resumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidateId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/uploads/cv1.pdf",
                            IsDefault = true,
                            RawTextContent = "Kinh nghiệm 3 năm làm việc với C#, chuyên sâu Web API, Entity Framework Core, SQL Server và Docker.",
                            Title = "CV Lê Văn Pro - .NET Developer"
                        },
                        new
                        {
                            Id = 2,
                            CandidateId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/uploads/cv2.pdf",
                            IsDefault = true,
                            RawTextContent = "Sinh viên mới tốt nghiệp, biết cơ bản về C# và OOP, chưa có kinh nghiệm thực tế hệ thống lớn.",
                            Title = "CV Nguyễn Thị Fresher"
                        },
                        new
                        {
                            Id = 3,
                            CandidateId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/uploads/cv3.pdf",
                            IsDefault = true,
                            RawTextContent = "Sinh viên năm 4 tìm kiếm vị trí thực tập, biết viết câu lệnh SQL cơ bản, đang học C#.",
                            Title = "CV Trần Văn Intern Backend"
                        },
                        new
                        {
                            Id = 4,
                            CandidateId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FilePath = "/uploads/cv4.pdf",
                            IsDefault = true,
                            RawTextContent = "Kinh nghiệm 2 năm chạy quảng cáo Facebook, Google Ads, tư vấn chốt đơn hàng.",
                            Title = "CV Hoàng Lệ - Sales Marketing"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayedName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quản trị viên toàn quyền hệ thống",
                            DisplayedName = "Quản trị viên",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhà tuyển dụng (Đăng tin, duyệt CV, dùng AI)",
                            DisplayedName = "Nhà tuyển dụng",
                            Name = "Recruiter"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ứng viên (Tìm việc, nộp CV)",
                            DisplayedName = "Ứng viên",
                            Name = "Candidate"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@ars.com",
                            FullName = "Hệ Thống Admin",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0123456789",
                            RoleId = 1,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "recruiter1@fpt.com",
                            FullName = "Nguyễn Văn Tuyển FPT",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0987654321",
                            RoleId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "recruiter2@viettel.com",
                            FullName = "Trần Thị Duyệt Viettel",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0912345678",
                            RoleId = 2,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "candidate1@gmail.com",
                            FullName = "Lê Văn Pro .NET",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0333444555",
                            RoleId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "candidate2@gmail.com",
                            FullName = "Nguyễn Thị Fresher",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0333444666",
                            RoleId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "candidate3@gmail.com",
                            FullName = "Trần Văn Intern",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0333444777",
                            RoleId = 3,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "candidate4@gmail.com",
                            FullName = "Hoàng Lệ Trái Ngành",
                            PasswordHash = "$2a$12$AZ2uR7y2CIwawpCEIjfrBOUtjC5PSpDFH5gWJn2Y0bgJUGGBkYvuy",
                            PhoneNumber = "0333444888",
                            RoleId = 3,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Application", b =>
                {
                    b.HasOne("Domain.Entities.User", "Candidate")
                        .WithMany("Applications")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Resume", "Resume")
                        .WithMany("Applications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("JobPosting");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Domain.Entities.Company", b =>
                {
                    b.HasOne("Domain.Entities.User", "Recruiter")
                        .WithOne("Company")
                        .HasForeignKey("Domain.Entities.Company", "RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.JobCategory", "JobCategory")
                        .WithMany("JobPostings")
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("Domain.Entities.RecruiterRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Resume", b =>
                {
                    b.HasOne("Domain.Entities.User", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.JobCategory", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Resume", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
